language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t oscarmr/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true oscarmr/docker-react npm run test
